[package]
name = "peekaboo"
version = "0.1.0"
authors = ["kujenga <git@ataylor.io>"]
edition = "2021"

[dependencies]
iron = "0.6"
serde = "1"
serde_derive = "1"
router = "0.6"
redis = "*"
image = "0.24"
num = "0.4"
time = "0.3"
urlencoded = "0.6"
handlebars = "4"
